# Generated by Django 2.0.7 on 2018-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_pic', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/')),
                ('photo_text', models.CharField(max_length=160)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
