# Generated by Django 2.0.7 on 2018-07-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.CharField(max_length=20)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Photo')),
            ],
        ),
    ]
