# Generated by Django 2.0.7 on 2018-07-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_pic',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_text',
            new_name='user',
        ),
    ]
