# Generated by Django 2.0.7 on 2018-07-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180712_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pub_date',
        ),
    ]
